alumnidata/urls.py
import imp
from django.urls import path
from alumnidata import views

urlpatterns = [
    path('', views.index, name="Homepage"),
    path('signup/', views.signup, name='signup'),
    path('login/', views.login_new, name='login'),
    path('logout/', views.logout_request, name='logout'),
    path('user/<int:id>/', views.userpage, name='user'),
    path('fofs/<int:id>/', views.fieldstudy_page, name='fofs'),
    path('job/<int:id>/', views.job_page, name='updatejob'),
    path('education/<int:id>/', views.education_page, name='updateeducation'),
    path('achievement/<int:id>/', views.achievement_page, name='updateachievement'),
    path('search/', views.searchdata_page, name="searchdata"),
]

cisalumni/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.static import serve
from django.conf.urls import url
from django.conf import settings

urlpatterns = [
    url(r'^alumnidata/static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),

    path('admin/', admin.site.urls),
    path('', include('alumnidata.urls')),
    path('accounts/', include('allauth.urls')),
]

alumnidata/models.py
from __future__ import unicode_literals
from django.db import models
from django.contrib.auth.models import User
from django.dispatch import receiver
from django.db.models.signals import post_save
from django.urls import reverse
from datetime import date

# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    role = models.CharField(max_length=15, default="#")

    @receiver(post_save, sender=User)
    def create_user_profile(sender, instance, created, **kwargs):
        if created:
            Profile.objects.create(user=instance)
    
    @receiver(post_save, sender=User)
    def save_user_profile(sender, instance, **kwargs):
        instance.profile.save()

    def __str__(self):
        return str(self.user)

class academicadmin(models.Model):
    gender_choices = [
        ("m", "male"),
        ("f", "female"),
        ("o", "lgbtqia2s+")
    ]

    academicadminID = models.CharField(max_length=10, default="#", null=False)
    academicadminName = models.OneToOneField(Profile, on_delete=models.CASCADE)
    phone = models.CharField(max_length=10, default="0123456789")
    dob = models.DateField(max_length=10, default=date.today)
    gender = models.CharField(max_length=10, choices=gender_choices, default="#")
    responsible = models.CharField(max_length=50, default="#")

    @receiver(post_save, sender=Profile)
    def save_admin_profile(sender, instance, **kwargs):
        if academicadmin.objects.filter(academicadminName=instance).count() != 0:
            print(academicadmin.objects.get(academicadminName=instance))
            
        elif academicadmin.objects.filter(academicadminName=instance).count() == 0 and instance.role == 'admin':
            academicadmin.objects.create(academicadminName=instance)

    def __str__(self):
        return str(self.academicadminName.user.first_name) + "," + str(self.academicadminName.user.last_name) + "," + str(self.academicadminName.role)

class assistantDean(models.Model):
    gender_choices = [
        ("m", "male"),
        ("f", "female"),
        ("o", "lgbtqia2s+")
    ]

    assistantDeanID = models.CharField(max_length=10, default="#", null=False)
    assistantDeanName = models.OneToOneField(Profile, on_delete=models.CASCADE)
    phone = models.CharField(max_length=10, default="0123456789")

    @receiver(post_save, sender=Profile)
    def save_dean_profile(sender, instance, **kwargs):
        if assistantDean.objects.filter(assistantDeanName=instance).count() != 0:
            print(assistantDean.objects.get(assistantDeanName=instance))
            
        elif assistantDean.objects.filter(assistantDeanName=instance).count() == 0 and instance.role == 'assistant_dean':
            assistantDean.objects.create(assistantDeanName=instance)

    def __str__(self):
        return str(self.assistantDeanName.user.first_name) + "," + str(self.assistantDeanName.user.last_name) + "," + str(self.assistantDeanName.role)

class fieldstudy(models.Model):
    alumniuser = models.OneToOneField(Profile, on_delete=models.CASCADE)
    studyField = models.CharField(max_length=80, default="#")
    studyMajor = models.CharField(max_length=80, default="#")
    studyMinor = models.CharField(max_length=80, default="#")
    yearStart = models.IntegerField(default=2543)
    yearGraduate = models.IntegerField(default=2547)
    gpa = models.FloatField(max_length=4, default=3.50)

    def __str__(self):
        return str(self.alumniuser.user.first_name) + ", " + str(self.studyField)
    

class job(models.Model):
    alumniuser = models.OneToOneField(Profile, on_delete=models.CASCADE)
    organization = models.CharField(max_length=255, default="#")
    organizeType = models.CharField(max_length=255, default="#")
    department = models.CharField(max_length=255, default="#")
    jobTitle = models.CharField(max_length=255, default="#")
    jobDesc = models.TextField(max_length=255, default="#")

    def __str__(self):
        return str(self.organization) + "," + str(self.department) + "," + str(self.jobTitle)

class education(models.Model):
    alumniuser = models.OneToOneField(Profile, on_delete=models.CASCADE)
    degree = models.CharField(max_length=10, default="#")
    university = models.CharField(max_length=255, default="#")
    faculty = models.CharField(max_length=255, default="#")
    major = models.CharField(max_length=255, default="#")
    country = models.CharField(max_length=255, default="#")

    def __str__(self):
        return str(self.degree) + "," + str(self.university) + "," + str(self.faculty)

class success(models.Model):
    alumniuser = models.OneToOneField(Profile, on_delete=models.CASCADE)
    achieveTitle = models.CharField(max_length=150, default="#")
    desc = models.TextField(max_length=2000, default="#")
    achieveDate = models.DateField(max_length=10, default=date.today)

    def __str__(self):
        return str(self.achieveTitle)

class alumnidata(models.Model):
    gender_choices = [
        ("m", "male"),
        ("f", "female"),
        ("o", "lgbtqia2s+")
    ]

    alumniuser = models.OneToOneField(Profile, on_delete=models.CASCADE)
    alumniID = models.CharField(max_length=10, default="#", null=False)
    phone = models.CharField(max_length=10, default="0123456789")
    dob = models.DateField(max_length=10, default=date.today)
    gender = models.CharField(max_length=10, choices=gender_choices, default="#")
    address = models.TextField(max_length=2500, default="#")
    
    @receiver(post_save, sender=Profile)
    def save_alumni_profile(sender, instance, **kwargs):
        if alumnidata.objects.filter(alumniuser=instance).count() != 0:
            print(alumnidata.objects.get(alumniuser=instance))
            
        elif alumnidata.objects.filter(alumniuser=instance).count() == 0 and instance.role == 'alumni':
            alumnidata.objects.create(alumniuser=instance)

    def __str__(self):
        return str(self.alumniuser.user.first_name) + "," + str(self.alumniuser.user.last_name) + "," + str(self.alumniuser.role)

class alumniList(models.Model):
    fieldstudy = models.CharField(max_length=50, default="#")
    yearGraduated = models.IntegerField(default=2543)
    studentID = models.CharField(max_length=10, default="#")
    firstname = models.CharField(max_length=50, default="#")
    lastname = models.CharField(max_length=50, default="#")

    def __str__(self):
        return str(self.firstname) + "," + str(self.lastname) + "," + str(self.studentID)

class adminList(models.Model):
    fieldresponible = models.CharField(max_length=50, default="#")
    adminID = models.CharField(max_length=10, default="#")
    firstname = models.CharField(max_length=50, default="#")
    lastname = models.CharField(max_length=50, default="#")
    phone = models.CharField(max_length=10, default="#")

    def __str__(self):
        return str(self.firstname) + "," + str(self.lastname)

class assistantDeanList(models.Model):
    assistantDeanID = models.CharField(max_length=10, default="#")
    firstname = models.CharField(max_length=50, default="#")
    lastname = models.CharField(max_length=50, default="#")
    phone = models.CharField(max_length=10, default="#")

    def __str__(self):
        return str(self.firstname) + "," + str(self.lastname)

alumnidata/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.forms import fields, widgets
from alumnidata.models import Profile


# Create your forms here.

class NewUserForm(UserCreationForm):
	email = forms.EmailField(max_length=254, required=True)
	username = forms.CharField(max_length=30, required=True, help_text=None)
	password1 = forms.CharField(max_length=30, min_length=8, required=True, help_text="Maximum is 30 character. Please use lowercase UPPERCASE and 0-9", widget=forms.PasswordInput)
	password2 = forms.CharField(max_length=30, min_length=8, required=True, help_text="Confirm Your Password", widget=forms.PasswordInput)

	class Meta:
		model = User
		fields = ("username", "first_name", "last_name", "email", "password1", "password2")

	def save(self, commit=True):
		user = super(NewUserForm, self).save(commit=False)
		user.email = self.cleaned_data['email']
		if commit:
			user.save()
		return user

class UserForm(forms.ModelForm):
	class Meta:
		model = User
		fields = ('username', 'first_name', 'last_name', 'email')

alumnidata/templates/achievement.htm
{% extends 'base.htm' %}
{% block section1 %}
<section class="contact-us" id="signup">
    <div class="container">
      <div class="row">
        <div class="col-lg-9 align-self-center">
          <div class="row">
            <div class="col-lg-12">

                <form method="POST" id="bigform">
                    {% csrf_token %}
  
                    <input type="text" name="title" maxlength="150" autofocus required id="id_title" placeholder="ชื่อผลงาน/รางวัล/อื่น ๆ">
  
                    <input type="date" name="achievedate" maxlength="30" autofocus required id="id_achievedate" placeholder="วันที่ได้รับรางวัล/ปฏิบัติงาน">
                        
                    <textarea type="text" name="desc" maxlength="255" id="id_desc" placeholder="รายละเอียด (พอสังเขป)"></textarea>
                    
                    <button type="submit"> Save </button>
                </form>

            </div>
          </div>
        </div>
        <div class="col-lg-3">
          <div class="right-info">
            <ul>
                <li>
                  <h6>Achievement</h6>
                  <span> {{usuccess.achieveTitle}} </span>
                </li>
                <br>
                <li>
                  <h6> Achieved Date </h6>
                  <span> {{usuccess.achieveDate}} </span>
                </li>
                <br>
                <li>
                  <h6> Update Data </h6>
                  <span> <a href="/user/{{ user.id }}/"> แก้ไขโปรไฟล์ </a> </span><br>
                  <span> <a href="/fofs/{{ user.id }}/"> ประวัติการศึกษา </a> </span><br>
                  <span> <a href="/job/{{ user.id }}/"> ประวัติการทำงาน </a> </span><br>
                  <span> <a href="/education/{{ user.id }}/"> การเรียนต่อ </a> </span><br>
                </li>

              </ul>
          </div>
        </div>
      </div>
    </div>
    <div class="footer">
      <p>Copyright © 2022 Edu Meeting Co., Ltd. All Rights Reserved. 
          <br>Design: <a href="https://templatemo.com" target="_parent" title="free css templates">TemplateMo</a></p>
    </div>
</section>
{% endblock %}

alumnidata/templates/education.htm
{% extends 'base.htm' %}
{% block section1 %}
<section class="contact-us" id="signup">
    <div class="container">
      <div class="row">
        <div class="col-lg-9 align-self-center">
          <div class="row">
            <div class="col-lg-12">

                <form method="POST" id="bigform">
                    {% csrf_token %}
                    <select name="degree">
                      <option value="" disabled selected hidden> ศึกษาต่อในระดับ </option>
                      <option type="text" value="bachelor"> ปริญญาตรี </option>
                      <option type="text" value="master"> ปริญญาโท </option>
                      <option type="text" value="PhD"> ปริญญาเอก </option>
                    </select>
  
                    <input type="text" name="university" maxlength="30" autofocus required id="id_university" placeholder="ชื่อมหาวิทยาลัย">
  
                    <input type="text" name="faculty" maxlength="30" autofocus required id="id_faculty" placeholder="สาขาวิชา">
                        
                    <input type="text" name="major" maxlength="150" id="id_major" placeholder="วิชาเอก">
                        
                    <input type="text" name="country" maxlength="255" id="id_country" placeholder="ศึกษาต่อที่ประเทศ">
                    
                    <button type="submit"> Save </button>
                </form>

            </div>
          </div>
        </div>
        <div class="col-lg-3">
          <div class="right-info">
            <ul>
                <li>
                  <h6>Study in</h6>
                  <span> {{uedu.degree}} </span>
                </li>
                <br>
                <li>
                  <h6> University </h6>
                  <span> {{uedu.university}}, {{uedu.country}} </span>
                </li>
                <br>
                <li>
                  <h6> Faculty </h6>
                  <span> {{uedu.faculty}} </span>
                </li>
                <br>
                <li>
                  <h6> Update Data </h6>
                  <span> <a href="/user/{{ user.id }}/"> แก้ไขโปรไฟล์ </a> </span><br>
                  <span> <a href="/fofs/{{ user.id }}/"> ประวัติการศึกษา </a> </span><br>
                  <span> <a href="/job/{{ user.id }}/"> ประวัติการทำงาน </a> </span><br>
                  <span> <a href="/achievement/{{ user.id }}/"> ผลงานที่เคยทำ </a> </span>
                </li>

              </ul>
          </div>
        </div>
      </div>
    </div>
    <div class="footer">
      <p>Copyright © 2022 Edu Meeting Co., Ltd. All Rights Reserved. 
          <br>Design: <a href="https://templatemo.com" target="_parent" title="free css templates">TemplateMo</a></p>
    </div>
</section>
{% endblock %}

alumnidata/templates/fieldstudy.htm
{% extends 'base.htm' %}
{% block section1 %}
<section class="contact-us" id="signup">
    <div class="container">
      <div class="row">
        <div class="col-lg-9 align-self-center">
          <div class="row">
            <div class="col-lg-12">
                <form method="POST" id="bigform">
                  {% csrf_token %}
                  <select name="studyField">
                    <option value="" disabled selected hidden> ระบุสาขาวิชา </option>
                    <option type="text" value="MA"> ปริญญาโท สตรี เพศสถานะ และเพศวิถีศึกษา (MA) </option>
                    <option type="text" value="DSI"> วิทยาศาสตรบัณฑิต สาขาวิชาวิทยาศาสตร์และนวัตกรรมข้อมูล (DSI) </option>
                    <option type="text" value="SI-LP"> ปริญญาตรีสหวิทยาการสังคมศาสตร์ (SI ลำปาง) </option>
                    <option type="text" value="PhD-IntegratedScience"> ปริญญาเอกสหวิทยาการ Ph.D. (Integrated Science) </option>
                    <option type="text" value="TUFT"> ปริญญาตรีหลักสูตร TU FRONTIER SCHOOL (ศูนย์รังสิต) </option>
                    <option type="text" value="PPE-TP"> สาขาวิชาปรัชญา การเมือง และเศรษฐศาสตร์ (PPE ท่าพระจันทร์) </option>
                    <option type="text" value="PPE-LP"> สาขาวิชาปรัชญา การเมือง และเศรษฐศาสตร์ (PPE ลำปาง) </option>
                    <option type="text" value="PPE-INTER-TP"> ปริญญาตรีปรัชญา การเมือง เศรษฐศาสตร์ หลักสูตรนานาชาติ (PPE International Program) </option>
                  </select>

                  <input type="text" name="major" maxlength="30" autofocus required id="id_major" placeholder="ระบุวิชาเอก">
                      
                  <input type="text" name="minor" maxlength="150" id="id_minor" placeholder="ระบุวิชาโท">
                      
                  <input type="number" name="start" maxlength="150" id="id_start" placeholder="ปีที่เริ่มศึกษา">
                          
                  <input type="number" name="stop" maxlength="254" required id="id_stop" placeholder="ปีที่จบการศึกษา">

                  <input type="number" step="any" name="gpa" maxlength="254" required id="id_gpa" placeholder="GPA ที่ได้">
                  
                  <button type="submit"> Save </button>
              </form>

            </div>
          </div>
        </div>
        <div class="col-lg-3">
          <div class="right-info">
            <ul>
                <li>
                  <h6>Field of Study</h6>
                  <span> {{ufofs.studyField}} </span>
                </li>
                <br>
                <li>
                  <h6> Major / Minor </h6>
                  <span> {{ufofs.studyMajor}} / {{ufofs.studyMinor}} </span>
                </li>
                <br>
                <li>
                  <h6> GPA </h6>
                  <span> {{ufofs.gpa}} </span>
                </li>
                <br>
                <li>
                  <h6> Update Data </h6>
                  <span> <a href="/user/{{ user.id }}/"> แก้ไขโปรไฟล์ </a> </span><br>
                  <span> <a href="/job/{{ user.id }}/"> ประวัติการทำงาน </a> </span><br>
                  <span> <a href="/education/{{ user.id }}/"> การเรียนต่อ </a> </span><br>
                  <span> <a href="/achievement/{{ user.id }}/"> ผลงานที่เคยทำ </a> </span>
                </li>

              </ul>
          </div>
        </div>
      </div>
    </div>
    <div class="footer">
      <p>Copyright © 2022 Edu Meeting Co., Ltd. All Rights Reserved. 
          <br>Design: <a href="https://templatemo.com" target="_parent" title="free css templates">TemplateMo</a></p>
    </div>
</section>
{% endblock %}

alumnidata/templates/job.htm
{% extends 'base.htm' %}
{% block section1 %}
<section class="contact-us" id="signup">
    <div class="container">
      <div class="row">
        <div class="col-lg-9 align-self-center">
          <div class="row">
            <div class="col-lg-12">

                <form method="POST" id="bigform">
                    {% csrf_token %}
                    <input type="text" name="organization" maxlength="150" autofocus required id="id_organization" placeholder="ชื่อองค์กร">
                    
                    <select name="organizationType">
                      <option value="" disabled selected hidden> ประเภทองค์กร </option>
                      <option type="text" value="บจก"> บริษัทจำกัด </option>
                      <option type="text" value="บมจ"> บริษัทมหาชนจำกัด </option>
                      <option type="text" value="หจก"> ห้างหุ้นส่วนจำกัด </option>
                      <option type="text" value="รัฐวิสาหกิจ"> รัฐวิสาหกิจ </option>
                      <option type="text" value="ภาครัฐ"> หน่วยงานภาครัฐ </option>
                      <option type="text" value="ธุรกิจส่วนตัว"> ธุรกิจส่วนตัว </option>
                    </select>

                    <select name="department">
                      <option value="" disabled selected hidden> แผนก/ฝ่าย </option>
                      <option type="text" value="administration"> บริหาร </option>
                      <option type="text" value="finance"> การเงิน </option>
                      <option type="text" value="accounting"> บัญชี </option>
                      <option type="text" value="HR"> ฝ่ายบุคคล </option>
                      <option type="text" value="IT"> ไอที </option>
                      <option type="text" value="operations"> ออเปอเรชั่น </option>
                      <option type="text" value="manufacture"> ฝ่ายผลิต </option>
                      <option type="text" value="PR"> ประชาสัมพันธ์ </option>
                      <option type="text" value="R&D"> วิจัยและพัฒนา </option>
                      <option type="text" value="sales"> ฝ่ายขาย </option>
                      <option type="text" value="marketing"> การตลาด </option>
                    </select>

                    <input type="text" name="jobTitle" maxlength="150" id="id_jobTitle" placeholder="ตำแหน่ง">
                        
                    <textarea type="text" name="jobDesc" maxlength="255" id="id_jobDesc" placeholder="หน้าที่งาน (พอสังเขป)"></textarea>
                    
                    <button type="submit"> Save </button>
                </form>

            </div>
          </div>
        </div>
        <div class="col-lg-3">
          <div class="right-info">
            <ul>
                <li>
                  <h6>Organization</h6>
                  <span> {{ujob.organization}} </span>
                </li>
                <br>
                <li>
                  <h6> Department </h6>
                  <span> {{ujob.department}} </span>
                </li>
                <br>
                <li>
                  <h6> Position </h6>
                  <span> {{ujob.jobTitle}} </span>
                </li>
                <br>
                <li>
                  <h6> Update Data </h6>
                  <span> <a href="/user/{{ user.id }}/"> แก้ไขโปรไฟล์ </a> </span><br>
                  <span> <a href="/fofs/{{ user.id }}/"> ประวัติการศึกษา </a> </span><br>
                  <span> <a href="/education/{{ user.id }}/"> การเรียนต่อ </a> </span><br>
                  <span> <a href="/achievement/{{ user.id }}/"> ผลงานที่เคยทำ </a> </span>
                </li>

              </ul>
          </div>
        </div>
      </div>
    </div>
    <div class="footer">
      <p>Copyright © 2022 Edu Meeting Co., Ltd. All Rights Reserved. 
          <br>Design: <a href="https://templatemo.com" target="_parent" title="free css templates">TemplateMo</a></p>
    </div>
</section>
{% endblock %}

alumnidata/templates/login.htm
{% extends 'base.htm' %}
{% load socialaccount %}

{% block section1 %}
<section class="contact-us" id="signup">
    <div class="container">
      <div class="row">
        <div class="col-lg-9 align-self-center">
          <div class="row">
            <div class="col-lg-12">
                <form method="POST" id="bigform">
                    {% csrf_token %}
                    <input type="text" name="username" autofocus autocapitalize="none" autocomplete="username" maxlength="150" placeholder="Enter Username" required id="id_username"> 
                    <input type="password" name="password" autocomplete="current-password" placeholder="Enter Password" required id="id_password">
                    <button type="submit"> Login </button>
                </form>
            </div>
          </div>
        </div>
        <div class="col-lg-3">
          <div class="right-info">
            <ul>
                <li>
                  <h6> ยังไม่มีบัญชีผู้ใช้งาน? </h6>
                  <span><a href="/signup/"> ลงทะเบียน </a></span>
                </li>
                <li>
                  <h6>Google</h6>
                  <span><a href="{% provider_login_url "google" %}" class="google">Login ด้วย Gmail</a></span>
                </li>
                <li>
                  <h6> ที่อยู่ </h6>
                  <span>ห้อง 118 อาคาร SC3 <br>
                    มหาวิทยาลัยธรรมศาสตร์ ศูนย์รังสิต <br>                    
                  </span>
                </li>
              </ul>
          </div>
        </div>
      </div>
    </div>
    <div class="footer">
      <p>Copyright © 2022 Edu Meeting Co., Ltd. All Rights Reserved. 
          <br>Design: <a href="https://templatemo.com" target="_parent" title="free css templates">TemplateMo</a></p>
    </div>
  </section>
{% endblock %}

alumnidata/templates/signup.htm
{% extends 'base.htm' %}

{% block section1 %}
<section class="contact-us" id="signup">
    <div class="container">
      <div class="row">
        <div class="col-lg-9 align-self-center">
          <div class="row">
            <div class="col-lg-12">
                <form method="POST" id="bigform">
                    {% csrf_token %}
                    <input type="text" name="username" maxlength="30" autofocus  required id="id_username" placeholder="Username"> <br>
                
                    <input type="text" name="first_name" maxlength="150"  id="id_first_name" placeholder="Firstname"> <br>
                
                    <input type="text" name="last_name" maxlength="150"  id="id_last_name" placeholder="Lastname"> <br>
                
                    <input type="email" name="email" maxlength="254"  required id="id_email" placeholder="Email Address"> <br>
                
                    <input type="password" name="password1" maxlength="30"  required id="id_password1" placeholder="Must have a-z, A-Z, 0-9"> <br>
                
                    <input type="password" name="password2" maxlength="30"  required id="id_password2" placeholder="Confirm Your Password"> <br>
                
                    <button type="submit">Sign Up Now</button>
                </form>
            </div>
          </div>
        </div>
        <div class="col-lg-3">
          <div class="right-info">
            <ul>
                <li>
                  <h6> หากมีบัญชีแล้ว </h6>
                  <span><a href="/login/"> เข้าสู่ระบบที่นี่ </a></span>
                </li>
                <li>
                  <h6> ช่องทางติดต่อ </h6>
                  <span> info@ci.tu.ac.th </span>
                </li>
                <li>
                  <h6> ที่อยู่ </h6>
                  <span>ห้อง 118 อาคาร SC3 <br>
                    มหาวิทยาลัยธรรมศาสตร์ ศูนย์รังสิต <br>                    
                  </span>
                </li>
              </ul>
          </div>
        </div>
      </div>
    </div>
    <div class="footer">
        <p>Copyright © 2022 Edu Meeting Co., Ltd. All Rights Reserved. 
            <br>Design: <a href="https://templatemo.com" target="_parent" title="free css templates">TemplateMo</a></p>
    </div>
</section>
{% endblock %}

alumnidata/templates/userpage.htm
{% extends 'base.htm' %}
{% block section1 %}
<section class="contact-us" id="signup">
    <div class="container">
      <div class="row">
        <div class="col-lg-9 align-self-center">
          <div class="row">
            <div class="col-lg-12">

                <form method="POST" id="bigform">
                    {% csrf_token %}
                    <input type="text" name="username" value="{{ user.username }}" maxlength="30" autofocus required id="id_username" placeholder="Username">
                        
                    <input type="text" name="first_name" value="{{ user.first_name }}" maxlength="150" id="id_first_name" placeholder="Firstname">
                        
                    <input type="text" name="last_name" value="{{ user.last_name }}" maxlength="150" id="id_last_name" placeholder="Lastname">
                            
                    <input type="email" name="email" value="{{ user.email }}" maxlength="254" required id="id_email" placeholder="Email Address">

                    <!-- <select name="role">
                        <option value="" disabled selected hidden> ระบุ Role ของท่าน </option>
                        <option type="text" value="alumni"> ศิษย์เก่า </option>
                        <option type="text" value="admin"> เจ้าหน้าที่ฝ่ายการนักศึกษา </option>
                        <option type="text" value="assistant_dean"> รองคณบดีฝ่ายการนักศึกษา </option>
                     </select> -->
                    
                    <button type="submit">Save Changes</button>
                </form>

            </div>
          </div>
        </div>
        <div class="col-lg-3">
          <div class="right-info">
            <ul>
                <li>
                  <h6>Welcome</h6>
                  <span> {{user.username}} </span>
                </li>
                <br>
                <li>
                  <h6> Fullname </h6>
                  <span> {{user.first_name}} {{user.last_name}} </span>
                </li>
                <br>
                <li>
                  <h6> Role </h6>
                  <span> {{profile.role}} </span>
                </li>
                {% if profile.role == "alumni" %}
                <br>
                <li>
                  <h6> Update Data </h6>
                  <span> <a href="/fofs/{{ user.id }}/"> ประวัติการศึกษา </a> </span><br>
                  <span> <a href="/job/{{ user.id }}/"> ประวัติการทำงาน </a> </span><br>
                  <span> <a href="/education/{{ user.id }}/"> การเรียนต่อ </a> </span><br>
                  <span> <a href="/achievement/{{ user.id }}/"> ผลงานที่เคยทำ </a> </span>
                </li>
                {% endif %}

              </ul>
          </div>
        </div>
      </div>
    </div>
    <div class="footer">
      <p>Copyright © 2022 Edu Meeting Co., Ltd. All Rights Reserved. 
          <br>Design: <a href="https://templatemo.com" target="_parent" title="free css templates">TemplateMo</a></p>
    </div>
</section>
{% endblock %}